name: sc4051-server

services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sc4051-server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/tcp"
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
      - "${SERVER_LOG_PORT}:${SERVER_LOG_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_LOG_PORT=${SERVER_LOG_PORT}
      - PACKET_DROP_RATE=${PACKET_DROP_RATE}
      - PACKET_TTL=${PACKET_TTL}
      - PACKET_TIMEOUT_RECEIVE=${PACKET_TIMEOUT_RECEIVE}
      - MESSAGE_ASSEMBLER_INTERVAL=${MESSAGE_ASSEMBLER_INTERVAL}
      - RESPONSE_TTL=${RESPONSE_TTL}
      - RESPONSE_INTERVAL=${RESPONSE_INTERVAL}
      - MATTERMOST_WEBHOOK=${MATTERMOST_WEBHOOK:-""}
    restart: unless-stopped
