version: "3"

tasks:

  ### Run sanity entry point
  sanity:
    desc: "Run sanity entry point"
    cmds:
      - go run ./cmd/sanity.go

  ### Testing Suite
  test:
    desc: "Run tests"
    cmds:
      - echo "Starting server tests"
      - go test ./internal/... -v --race

  ### Execute server (locally)
  start:
    desc: "Starts server"
    cmds:
      - go run ./cmd/server.go