name: Server Tests

on:
  push:
    paths:
      - "**/*.go"
    branches:
      - main
  pull_request:
    paths:
      - "**/*.go"
    branches:
      - main

jobs:
  server-go-tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: [1.23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./server

      - name: Server Go Tests
        run: go test ./internal/... -v --race
        working-directory: ./server